# Generated by Django 4.2.7 on 2023-12-21 19:15

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=144)),
                (
                    "media",
                    models.ImageField(
                        blank=True, upload_to=social_media.models.post_file_path
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=144)),
                (
                    "media",
                    models.ImageField(
                        blank=True, upload_to=social_media.models.post_file_path
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
