# Generated by Django 4.2.7 on 2024-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="liked_comments",
        ),
        migrations.RemoveField(
            model_name="user",
            name="liked_posts",
        ),
    ]
